### ISSUE TITLE
Getting ErrorInvalidRecipients Error 

### ISSUE THREAD

**Issue by rubydwebguys** [microsoftgraph/php-connect-rest-sample#39] opened 2017-07-27 12:44 UTC
Hi 

I set up this project as suggested in https://github.com/microsoftgraph/php-connect-sample it works fine till authorization but when using send mail code it gives me invalid recipient error

ClientException in RequestException.php line 111:
Client error: `POST https://graph.microsoft.com/v1.0/me/sendMail` resulted in a `400 Bad Request` response:
{
"error": {
"code": "ErrorInvalidRecipients",
"message": "At least one recipient isn't valid., A message c (truncated...)
in RequestException.php line 111
at RequestException::create(object(Request), object(Response)) in Middleware.php line 65
at Middleware::GuzzleHttp\{closure}(object(Response)) in Promise.php line 203
at Promise::callHandler('1', object(Response), array(object(Promise), object(Closure), null)) in Promise.php line 156
at Promise::GuzzleHttp\Promise\{closure}() in TaskQueue.php line 47
at TaskQueue->run(true) in Promise.php line 246
at Promise->invokeWaitFn() in Promise.php line 223
at Promise->waitIfPending() in Promise.php line 266
at Promise->invokeWaitList() in Promise.php line 225
at Promise->waitIfPending() in Promise.php line 62
at Promise->wait() in Client.php line 129
at Client->request('POST', 'v1.0/me/sendMail', array('body' => '{"message":{}}', 'stream' => null, 'timeout' => '0')) in GraphRequest.php line 247
at GraphRequest->execute() in EmailController.php line 109
at EmailController->sendEmail()
at call_user_func_array(array(object(EmailController), 'sendEmail'), array()) in compiled.php line 9567
at Controller->callAction('sendEmail', array()) in compiled.php line 9594
at ControllerDispatcher->dispatch(object(Route), object(EmailController), 'sendEmail') in compiled.php line 8648
at Route->runController() in compiled.php line 8629
at Route->run(object(Request)) in compiled.php line 8338
at Router->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 10160
at SubstituteBindings->handle(object(Request), object(Closure)) in compiled.php line 10052
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 3309
at VerifyCsrfToken->handle(object(Request), object(Closure)) in compiled.php line 10052
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 13725
at ShareErrorsFromSession->handle(object(Request), object(Closure)) in compiled.php line 10052
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 12131
at StartSession->handle(object(Request), object(Closure)) in compiled.php line 10052
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 13471
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure)) in compiled.php line 10052
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 13408
at EncryptCookies->handle(object(Request), object(Closure)) in compiled.php line 10052
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 10037
at Pipeline->then(object(Closure)) in compiled.php line 8339
at Router->runRouteWithinStack(object(Route), object(Request)) in compiled.php line 8330
at Router->dispatchToRoute(object(Request)) in compiled.php line 8321
at Router->dispatch(object(Request)) in compiled.php line 2575
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 3371
at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in compiled.php line 10052
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 10037
at Pipeline->then(object(Closure)) in compiled.php line 2519
at Kernel->sendRequestThroughRouter(object(Request)) in compiled.php line 2503
at Kernel->handle(object(Request)) in index.php line 54
at require_once('D:\xampp\htdocs\outlook\public\index.php') in server.php line 21

**Comment by biroplane** [comment] 2017-10-10 14:06
+1

**Comment by jamescro** [comment] 2017-10-10 16:24
I can't reproduce this.  Are you sending the email to the same account that you used to authenticate? What is the domain of the email?

**Comment by rubydwebguys** [comment] 2017-10-11 06:21
I resolved this a long ago.

**Comment by jamescro** [comment] 2017-10-11 15:28
Thanks for the update. Closing for now.

**Closed by jamescro** 2017-10-11 15:28 UTC

**Comment by jscottk** [comment] 2018-07-27 23:23
Any insight into how you resolved this @rubydwebguys ?
